import { useState } from "react";
import "./App.css";
import "./components/Letters";
import "./components/InputCode";
import InputCode from "./components/InputCode";
import OutputCode from "./components/Outputcode";

function App({ Letters }) {
  const [encryption, setEncryption] = useState("");
  const letters = {
    alphabet: [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
    ],
    plugboard: [
      "Z",
      "P",
      "H",
      "N",
      "M",
      "S",
      "W",
      "C",
      "I",
      "Y",
      "T",
      "Q",
      "E",
      "D",
      "O",
      "B",
      "L",
      "R",
      "F",
      "K",
      "U",
      "V",
      "G",
      "X",
      "J",
      "A",
    ],
    fastRotor: [
      "E",
      "K",
      "M",
      "F",
      "L",
      "G",
      "D",
      "Q",
      "V",
      "Z",
      "N",
      "T",
      "O",
      "W",
      "Y",
      "H",
      "X",
      "U",
      "S",
      "P",
      "A",
      "I",
      "B",
      "R",
      "C",
      "J",
    ],
    mediumRotor: [
      "A",
      "J",
      "D",
      "K",
      "S",
      "I",
      "R",
      "U",
      "X",
      "B",
      "L",
      "H",
      "W",
      "T",
      "M",
      "C",
      "Q",
      "G",
      "Z",
      "N",
      "P",
      "Y",
      "F",
      "V",
      "O",
      "E",
    ],
    slowRotor: [
      "B",
      "D",
      "F",
      "H",
      "J",
      "L",
      "C",
      "P",
      "R",
      "T",
      "X",
      "V",
      "Z",
      "N",
      "Y",
      "E",
      "I",
      "W",
      "G",
      "A",
      "K",
      "M",
      "U",
      "S",
      "Q",
      "O",
    ],
    reflectorA: [
      "E",
      "J",
      "M",
      "Z",
      "A",
      "L",
      "Y",
      "X",
      "V",
      "B",
      "W",
      "F",
      "C",
      "R",
      "Q",
      "U",
      "O",
      "N",
      "T",
      "S",
      "P",
      "I",
      "K",
      "H",
      "G",
      "D",
    ],
    reflectorB: [
      "Y",
      "R",
      "U",
      "H",
      "Q",
      "S",
      "L",
      "D",
      "P",
      "X",
      "N",
      "G",
      "O",
      "K",
      "M",
      "I",
      "E",
      "B",
      "F",
      "Z",
      "C",
      "W",
      "V",
      "J",
      "A",
      "T",
    ],
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Enigma</h1>
        <p>Made with React</p>
      </header>
      <div>
        <InputCode
          encryptionText={encryption}
          onChange={(e) => setEncryption(e.target.value)}
        ></InputCode>
        <p>Plugboard: {letters.plugboard[0]}</p>
        <p>Fast Wheel: {letters.fastRotor[0]}</p>
        <p>Medium Wheel: {letters.mediumRotor[0]}</p>
        <p>Slow Wheel: {letters.slowRotor[0]}</p>
        <p>Reflector: {letters.reflectorA[0]}</p>
        <p>Slow Wheel: {letters.slowRotor[0]}</p>
        <p>Medium Wheel: {letters.mediumRotor[0]}</p>
        <p>Fast Wheel: {letters.fastRotor[0]}</p>
        <p>Plugboard: {letters.plugboard[0]}</p>
        <OutputCode result={encryption}></OutputCode>
      </div>
    </div>
  );
}

export default App;
